### ISSUE TITLE
VAL101

### ISSUE THREAD

**Issue by Tatianabellagio** [FlukeAndFeather/jese4sci-VAL#10]
How do you check that your code works?
Most times I try to run all of it and see if i get errors. When I am working in a more complex script that calls other scripts that contain multiple functions I make my scripts full of informative prints like print('phase 1 works!!'). I am not sure

Pick an R package you use frequently. Find an issue associated with a fixed bug. For example, here's an issue for a bug in plotly with x-axis dates. Hint: you'll have to search for closed issues. Regarding your issue:
Summarize the bug

This issue https://github.com/tidyverse/ggplot2/issues/4653 is from ggplot package in R. The bug is that lineend is inconsistent in different plots. The bug was solved in https://github.com/tidyverse/ggplot2/pull/4664

Was there a conversation about what caused the bug or how to fix it? There was actually no discussion about it. The author just fixed it. 
How many lines of code changed in the fix? Hint: look for an entry that says "[username] pushed a commit that referenced this issue..." 
It seems like the fix only took a few lines of code, but he made other modifications so ended up committing 4 times and changing many lines of code

**Comment by cypayne** [comment]
Great!
