### ISSUE TITLE
VAL101

### ISSUE THREAD

**Issue by raecv** [FlukeAndFeather/jese4sci-VAL#11]
1. How do you check that your code works?

You can set up tests to make sure you get the results you expect when you run your code. 

2. Pick an R package you use frequently. Find an issue associated with a fixed bug. 
Summarize the bug. Was there a conversation about what caused the bug or how to fix it? How many lines of code changed in the fix?

ggrepel bug: https://github.com/slowkow/ggrepel/issues/200

Someone noticed that if you try to control the alignment of text within boxes with `hjust` it affects both the text and the boxes they are in. The user suggested fixing it by adding arguments to `hjust` to control text and boxes separately: `label.hjust` and `box.hjust` respectively.

In the conversation the user provided reprex and related issues. Most people argreed with the suggestions they gave to split it in two, since this is consistent with ggplot2 logic. They eventually opened a feature request. I think eventually they fixed it by using `positiion_nudge_to()` from the ggpp package, so not many lines of code at all.

**Comment by cypayne** [comment]
Great!
