### ISSUE TITLE
VAL102

### ISSUE THREAD

**Issue by ggsun** [FlukeAndFeather/jese4sci-VAL#13]
Q1. A common error I encounter is "divide by zero" errors when unexpected zeros are encountered in division operations. There are also "key errors" that are associated with providing wrong key names (usually due to typos) for dataframes, dictionaries etc.

Q2. If `is.numeric(x)` returns `FALSE`, or in other words, if `x` is not a number, the `stop()` function will be called which stops the code from running and an error message will be printed to the console.

Q3. 
```
long_fun <- function(x) {
  if(!(is.numeric(x))) 
    stop("Error: `x` must be a number.")
  
  # Do
  # something
  # that 
  # takes
  # a
  # really
  # long
  # time
  long_running_subprocess()
  
  # Assume `x` is a number
  needs_a_number(x)
}
long_fun("definitely not a number")
```

I'm looking at this function for the rest of the questions here:
https://github.com/Bioconductor/Biostrings/blob/1403218126c1cfd0cfce14f1708518ce80f1d889/R/translate.R#L94

1. There is an assertion that checks if `no.init.codon`, one of the arguments to the function, is boolean.
2. I would add an assertion that checks that arguments `x` is a valid DNA sequence, because it seems that the function is deferring this check to the C function that is being called later in the code. The assertion would look something like this:

```
x_bases <- strsplit(x)[[1]]
for (base in x_bases) {
  if(!(base %in% DNA_BASES)) {
    stop('Invalid DNA base found in sequence `x`.')
  }
}
```

3. The error messages are pretty inconsistent in terms of quality. Some were very descriptive as to showing what exactly was the input that led to the error (e.g. `stop("'rownames(", argname, ")' must be the 4 DNA bases ('DNA_BASES')")`), while others gave no account of the nature of the error itself (e.g. `stop("fatal error")`). I would try to search for these vague error messages and try to make them as descriptive as possible.

**Comment by cypayne** [comment]
great!
