### ISSUE TITLE
VAL101

### ISSUE THREAD

**Issue by hffung** [FlukeAndFeather/jese4sci-VAL#14]
1. I run each line and check the outputs e.g. if I'm manipulating a data frame, I'll run str() to check the data frame.

2. **lme4:** https://github.com/lme4/lme4/issues/631
    i. Calling predict() on a mixed effects model yielded the error, "object is not a matrix".
    ii. Yes, there was a conversation between the user and developer in which the developer identified additional inputs that yield the same error message.
   iii. Fixing the bug required modifying two files with 23 additions and one deletion: https://github.com/lme4/lme4/commit/c3aae2c3c907fba88f93e6d4712f95497750a55c

**Comment by cypayne** [comment]
Great!
