### ISSUE TITLE
VAL101

### ISSUE THREAD

**Issue by tomjhandley** [FlukeAndFeather/jese4sci-VAL#15]
1. How do you check that your code works?
- I normally try to run it on a small subset of the data to see if the results are intelligible and/or depending on the section of code, try to manually check a small section of it to see if it is behaving in the way that I think it should. 
 
Pick an R package you use frequently. Find an issue associated with a fixed bug. For example, here's an issue for a bug in plotly with x-axis dates. Hint: you'll have to search for closed issues. 

2. Issue: 
https://github.com/tidyverse/ggplot2/issues/4653
- Summarize the bug: in ggplot2 - Visual discrepancies between what is shown in different keys and in the plot.
- Was there a conversation about what caused the bug or how to fix it?: Short conversation from developer, referenced an earlier issue: https://github.com/tidyverse/ggplot2/issues/4507
- How many lines of code changed in the fix? Hint: look for an entry that says "[username] pushed a commit that referenced this issue..." #52 (https://github.com/tidyverse/ggplot2/pull/4664/commits/f4b7f2fb02bbc60c6601b6757b81b1c9ae5875e3)

**Comment by cypayne** [comment]
Great!
