### ISSUE TITLE
VAL101

### ISSUE THREAD

**Issue by gpreising** [FlukeAndFeather/jese4sci-VAL#5]
Q1: Generally speaking, I will throw a couple datasets at my code to make sure it works.  A lot of my experience with coding was with biological networks in undergrad, so I will use examples from that. If I write a network algorithm, I need to make sure it is generalizable to different types of networks including really small ones, really big ones, disconnected ones, completely connected ones, ones with self-edges etc. By testing extremes as well as what I actually want to analyze, I can usually see if my code works. 

Q2: Okay so I'm looking at [phytools](https://github.com/liamrevell/phytools/issues/27). Broadly, there was a line that relied on automatic matching with $ (e.g. tree$tip), which can break if the tree/phylo object is modified. The poster and the author did have a conversation about it and the bug was fixed. 6 (3ins/3del) lines of code were changed.

**Comment by cypayne** [comment]
Sweet!
