### ISSUE TITLE
VAL101

### ISSUE THREAD

**Issue by ggsun** [FlukeAndFeather/jese4sci-VAL#6]
1. I usually think of as many simple test inputs as I can, inside the reasonable range of inputs that I might expect from the code's usage. I make sure the code returns the results that I would expect from those simple test inputs.

2. I looked into this bug: https://github.com/tidyverse/ggplot2/issues/4624

- When using the `geom_point()` function, the user reported that if they set the `stroke` argument to be `NA` to remove the borders of the points, setting the `size` argument no longer has any affect on the size of the points that are displayed on the plot.
- There was a fair amount of discussion on what causes this bug and how to fix it, including temporary solutions that might resolve the issue without changing the codebase. Eventually the conclusion was that if `stroke` was set to `NA`, it should be reset to zero when calculating the size of the points to keep it from messing up its calculations.
- 6 lines of code were added, and 1 line removed.

**Comment by cypayne** [comment]
Great!
